## Naive Seed Hacking

```{r, echo=FALSE}
box::use(dplyr[...])
box::use(purrr[...])
box::use(furrr[...])
box::use(progressr[...])
box::use(future[...])
box::use(palmerpenguins[penguins])
box::use(tidyr[drop_na])

## This is what's being 'injected' into the environment by Rscript -e "..."
# set.seed <- function(s){
#     base::set.seed(42)
# }

coin_flip <- function(n){
    res = sample(c(1,0), size=n, replace=TRUE)
    return(res)
}

read_data_transparently_published_on_osf <- function(identifier){
    project = osfr::osf_retrieve_node(paste0("https://osf.io/", identifier
    ,"/")) |> osfr::osf_ls_files()
    data_summary = osfr::osf_download(project, conflict="skip")
    df = read.csv(data_summary[["local_path"]]) 
    return(df)
}
```

```{r}
set.seed(Sys.time())
data = read_data_transparently_published_on_osf("dw2rz")

predictions = coin_flip(nrow(data))
cat("Accuracy: ", mean(predictions == data$label), "\n")
```

```{r, echo=FALSE}

## Change the model slightly so it's not obvious the seed is being forced by the environment
coin_flip <- function(n){
    res = sample(c(1,0), size=n, replace=TRUE)
    res[i] = 0
    res[i+1]= 0
    res[i+2]= 0
    return(res)
}
```

```{r}
starting_seed = Sys.time()
for (i in 1:5){
    set.seed(starting_seed+i)
    predictions = coin_flip(nrow(data))
    cat("Accuracy: ", mean(predictions == data$label), "\n")
}
```
